name: Build and Publish SkyHigh.PocoEntity.Generator NuGet Package

on:
  push:
    branches: [ main ]
    tags:
      - 'peg-v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for GitVersion
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    # The cd command in a separate step doesn't persist between steps
    # Instead, we'll use full paths for all commands
        
    - name: Restore dependencies
      run: dotnet restore src/PocoEntity/SkyHigh.PocoEntity.sln
      
    - name: Build
      run: dotnet build src/PocoEntity/SkyHigh.PocoEntity.Generator/SkyHigh.PocoEntity.Generator.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/PocoEntity/SkyHigh.PocoEntity.sln --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Pack
      run: dotnet pack src/PocoEntity/SkyHigh.PocoEntity.Generator/SkyHigh.PocoEntity.Generator.csproj --configuration Release --no-build --output ./nuget-packages
      
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nuget-packages/*.nupkg
        
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/peg-v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages
        path: ./nuget-packages
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Publish to NuGet
      run: |
        # Extract version from tag name (removes 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/peg-v}
        echo "Publishing version $VERSION to NuGet"
        
        # Push the package to NuGet
        dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate